# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: wyzdwdz/appimage-build
      
      - name: Build and push Docker image amd64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile_x86_64_ubuntu
          push: false
          tags: ${{ steps.meta.outputs.tags }}-amd64
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push Docker image arm64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile_arm64_ubuntu
          push: false
          tags: ${{ steps.meta.outputs.tags }}-arm64
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@0.3.1
        with:
          inputs: ${{ steps.meta.outputs.labels }}
          images: ${{ steps.meta.outputs.labels }}-arm64,${{ steps.meta.outputs.labels }}-arm64
          push: true
